# 1. Tổng quan

AI hiện nay không còn là vấn đề xa lạ đối với chúng ta nữa, với sự phát triển  về tài nguyên thiết bị phần cứng cùng một khối lượng dữ liệu khổng lồ đã tạo điều kiện cho AI phát triển mạnh mẽ và có thể được áp dụng cho nhiều lĩnh vực, ngành nghề khác nhau như an ninh - quốc phòng, y tế, giao thông, giáo dục, thương mại điện tử,... Trong lĩnh vực giao thông, chúng ta có thể thấy được những hệ thống thống kê giám sát giao thông thông minh như phát hiện phương tiện vi phạm giao thông (vượt đèn đỏ, chạy quá tốc độ, ...), hệ thống thống kê lưu lượng phương tiện giao thông trên một số tuyến đường. Trong lĩnh vực y tế, AI có khả năng giúp bác sĩ vạch liệu trình xạ trị cho bệnh nhân ung thư (Báo thanh niên: [link](https://thanhnien.vn/cong-nghe/ai-vach-lieu-trinh-xa-tri-cho-benh-nhan-ung-thu-trong-20-phut-989519.html) ).Cách đây không lâu, VinBigData đã công bố về bộ dữ liệu "VinBigData Chest X-ray Abnormalities Detection" nhằm phục vụ cho quá trình nghiên cứu ứng dụng AI phát hiện bệnh về phổi (Thông tin dữ liệu tại [**đây**](https://www.kaggle.com/c/vinbigdata-chest-xray-abnormalities-detection)). Hay gần đây nhất, thành phố HCM đang triển khai hệ thống callbot - qua đó AI có thể gọi điện thoại cho người dân và phát hiện người nói có bị mắc covid hay không thông qua tiếng ho của họ (thông tin chi tiết tại [**link**](https://www.covid.aihub.vn/?fbclid=IwAR34TJSbRZfvRZqzBejnpa9tKtfNTCayo9XPREcHCF9E5wNb07h3ONngBXg)). Chúng ta có thấy bất ngờ khi nghe nhạc, xem phim trên youtube thì gần như ngay lập tức youtube đã đề xuất cho chúng ta những bài nhạc, bộ phim có chủ đề tương tự. Hay việc mua đồ trên một số trang thương mại điện tử, những trang web này có thể đề xuất cho chúng ta một cách nhanh chóng những sản phẩm phù hợp với sở thích - đây chính là khả năng của một hệ thống khuyến nghị (recommendation system). Từ đó thấy được rằng AI như một cộng sự đồng hành và hỗ trợ cho con người trong cuộc sống.

Vậy toán học có ý nghĩa như thế nào đối với AI nói chung và một hệ thống AI nói riêng? Có thể nói, toán như là "trái tim" của AI vậy. Từ các mô hình Machine Learning cơ bản cho đến các mô hình Deep Learning phức tạp đều được xây dựng và phát triển dựa trên công thức toán học. Không chỉ dừng lại ở việc xây dựng và phát triển công thức toán học cho một mô hình mà còn phải tìm cách tối ưu nó - vì vậy, khi nắm vững kiến thức toán chúng ta có thể hiểu được và tinh chỉnh mô hình Machine Learning hay Deep Learning trở nên tốt hơn. Hình dưới đây sẽ cho chúng ta thấy được tầm quan trọng của toán học trong lĩnh vực Machine Learning, Deep Learning.

![image](https://miro.medium.com/max/800/0*xxYrThCJXugbESV3.png)

Bài viết này mình sẽ bắt đầu từ phần chiếm tỷ lệ lớn nhất trong biểu đồ trên đó là đại số tuyến tính. Để bắt đầu với nó mình sẽ trình bày một số khái niệm cơ bản của đại số tuyến tính bao gồm:
- Vector
- Norm
- Matrix

# 2. Numpy

Numpy (Numerical Python) - là một thư viện bao gồm các đối tượng mảng đa chiều (multidimentional array) và một tập hợp các phương thức để có thể xử lý mảng đó. Với numpy ta có thể sử dụng sụng các toán tử toán học, logic cùng các phương thức xử lý mảng để thực hiện trên đối tượng mục tiêu.
![numpy](https://i.imgur.com/mg8O3kd.png)

Sau đây là một số ưu điểm của numpy:
- Chứa bộ các giá trị.
- Có thể chứa các kiểu dữ liệu khác nhau.
- Có thể thêm, xóa, sửa.
- Có đầy đủ chức năng tính toán.

Và theo suốt bài viết này, mình sẽ sử dụng numpy làm chương trình minh họa cho việc biểu diễn vector, ma trận và một số thao tác xử lý và tính toán trên chúng.

# 3. Vector

Vector là một tuple của một hoặc nhiều giá trị vô hướng. Các vector được xây dựng từ các thành phần là các ordinary number (các kiểu int, float, ...). Có thể xem vector như một danh sách các số và đại số vector là các phép toán thực hiện trên các số bên trong danh sách đó. 

Tên một vector là chữ thường - được ký hiệu như sau:
$$
  v = (x_1, x_2, x_3, ..., x_n)
$$
Trong đó: 
- v là vector.
- $x_1, x_2, x_3, ..., x_n$ là các giá trị vô hướng

Một vector có thể được biểu diễn theo chiều ngang hoặc chiều dọc
$$
\begin{bmatrix}
   x_1 \\
   x_2 \\
   x_3 \\
   ... \\
   x_n
\end{bmatrix}
$$

## a. Tạo một vector

In [1]:
import numpy as np 

In [2]:
v = np.array([1, 2, 3, 4, 5])
print(v)

[1 2 3 4 5]


### Tạo vector từ list, tuple

In [3]:
# Tạo vector từ list
list_vector = [1, 2, 3, 4, 5]
v = np.asarray(list_vector)
v

array([1, 2, 3, 4, 5])

In [4]:
# Tạo vector từ tuple
tuple_vector = (1, 2, 3, 4, 5)
v = np.asarray(tuple_vector)
v

array([1, 2, 3, 4, 5])

### Tạo vector gồm các phần tử có gián trị mặc định là 0 hoặc 1

In [5]:
# Tạo một vector 0
v = np.zeros(5)
v

array([0., 0., 0., 0., 0.])

In [6]:
# Tạo một vector 1
v = np.ones(5)
v

array([1., 1., 1., 1., 1.])

In [7]:
vector_a = np.array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# Tạo 1 vector 0 có kích thước giống vector_a
v = np.zeros_like(vector_a)
v

array([0, 0, 0, 0, 0, 0, 0])

In [9]:
# Tạo 1 vector 1 có kích thước giống vector_a
v = np.ones_like(vector_a)
v

array([1, 1, 1, 1, 1, 1, 1])

### Tạo vector với range
sử dụng numpy.arange(start, stop, step, dtype)

In [10]:
v = np.arange(10, 50, 5)
v

array([10, 15, 20, 25, 30, 35, 40, 45])

## b. Một số thao tác trên mảng

### Kiểm tra kích thước của mảng
Kết quả trả ra sẽ là một tuple với mỗi phần tử trong tuple tương ứng với kích thước của mỗi chiều trong mảng

In [11]:
v.shape

(8,)

### Cập nhật phần tử của mảng

In [12]:
print(v)
v[0] = 999
print(v)

[10 15 20 25 30 35 40 45]
[999  15  20  25  30  35  40  45]


### Truy xuất phần tử trên mảng

In [13]:
print(v)
print(v[2]) # lầy phần tử thứ 2 trong mảng
print(v[:]) # lấy toàn bộ mảng
print(v[::-1]) # đảo ngược mảng
print(v[1:4]) # lấy các phần tử có index từ 1->4
print(v[v<40]) # lấy các phần tử nhỏ hơn 40

[999  15  20  25  30  35  40  45]
20
[999  15  20  25  30  35  40  45]
[ 45  40  35  30  25  20  15 999]
[15 20 25]
[15 20 25 30 35]


### Thêm phần tử vào cuối mảng

In [14]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
v = np.append(v, 100)
print(v)

[  1   2   3   4   5   6   7   8   9 100]


### Thêm phần tử vào index trong mảng

In [15]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
v = np.insert(v, 3, 100)
print(v)

[  1   2   3 100   4   5   6   7   8   9]


### Xóa phần tử thứ index trong mảng

In [16]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
v = np.delete(v, 4)
print(v)

[1 2 3 4 6 7 8 9]


### Copy mảng

In [17]:
%%time 

v = np.array([1, 2, 3, 4, 5])
v_copy = v 
print(v)
print(v_copy)

[1 2 3 4 5]
[1 2 3 4 5]
CPU times: user 1.09 ms, sys: 871 µs, total: 1.96 ms
Wall time: 2.47 ms


In [18]:
%%time 

v = np.array([1, 2, 3, 4, 5])
v_copy = v [:]
print(v)
print(v_copy)

[1 2 3 4 5]
[1 2 3 4 5]
CPU times: user 2.01 ms, sys: 0 ns, total: 2.01 ms
Wall time: 2.26 ms


In [19]:
%%time

v = np.array([1, 2, 3, 4, 5])
v_copy = v.copy()
print(v)
print(v_copy)

[1 2 3 4 5]
[1 2 3 4 5]
CPU times: user 2 ms, sys: 0 ns, total: 2 ms
Wall time: 2.55 ms


Bên cạnh 3 cách trên chúng ta có thể sử dụng view để copy 1 mảng

In [20]:
%%time
v = np.array([1, 2, 3, 4, 5])
v_copy = v.view()
print(v)
print(v_copy)

[1 2 3 4 5]
[1 2 3 4 5]
CPU times: user 1.87 ms, sys: 0 ns, total: 1.87 ms
Wall time: 2.15 ms


Tuy thời gian thực thi của hàm view có nhanh hơn copy() nhưng hãy cẩn thận với view() vì khi thay đổi mảng ban đầu thì mảng copy cũng sẽ bị thay đổi

In [21]:
v = np.array([1, 2, 3, 4, 5])
v_copy = v.view()
print(v)
print(v_copy)

v[0] = 999
print(v)
print(v_copy)

[1 2 3 4 5]
[1 2 3 4 5]
[999   2   3   4   5]
[999   2   3   4   5]


## c. Các phép toán số học

### Cộng hai vector
$$
c = a + b
$$
$$
c = (a_1+b_1, a_2+b_2, ..., a_n+b_n)
$$

In [22]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

c = a + b 
print(c)

[3 5 7]


### Trừ hai vector
$$
c = a - b
$$
$$
c = (a_1-b_1, a_2-b_2, ..., a_n-b_n)
$$

In [24]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

c = b - a 
print(c)

[1 1 1]


# Nhân hai vector
$$
c = a * b
$$
$$
c = (a_1*b_1, a_2*b_2, ..., a_n*b_n)
$$

In [25]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

c = a * b
print(c)

[ 2  6 12]


# Chia hai vector
$$
c = a / b
$$
$$
c = (a_1/b_1, a_2/b_2, ..., a_n/b_n)
$$

In [28]:
a = np.array([4, 6, 8])
b = np.array([2, 3, 4])

c = a / b
print(c)

[2. 2. 2.]


### Vector dot product
- Có thể tính tổng các phần tử nhân của hai vector có cùng độ dài để được kết quả vô hướng. Ta gọi nó là dot product (ký hiệu: ".")
- Dot product còn là một công cụ để tính toán các phép chiếu vector (vector projection), phân tách vector (vector decomposition), xác định tính trực giao (orthogonality)

$$
c = a.b
$$
$$
c = a_1*b_1+a_2*b_2+...+a_n*b_n
$$

In [29]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

c = a.dot(b)
print(c)

20


### Vector-Scalar Multiplication (phép nhân vector - vô hướng)
- Một vector có thể nhân với một giá trị vô hướng => nhân rộng độ lớn (scale)của vector.
- Sử dụng ký hiệu **s** để biểu thị giá trị vô hướng
$$
c = s*v 
$$
$$
c = (s*v_1,s*v_2,...,s*v_n)
$$

In [30]:
v = np.array([1, 2, 3])
s = 5
c = v * s
print(c) 

[ 5 10 15]


## d. Một số hàm thống kê cơ bản

### Tìm max, min

In [35]:
v = np.array([1, 2, 3, 4, 5])
print("max: ", np.amax(v))
print("min: ", np.amin(v))

max:  5
min:  1


### Tính giá trị trung bình

In [36]:
v = np.array([1, 2, 3, 4, 5])
print("mean: ", np.mean(v))

mean:  3.0


### Giá trị trung vị
Lấy trung bình phần tử ở giữa mảng

In [38]:
v = np.array([1, 2, 3, 4, 5, 6])
print("median: ", np.median(v))

median:  3.5


# 4. Vector Norm
Độ dài của vector là một số **không âm** mô tả phạm vi của vector trong không gian và còn được gọi là độ lớn vector (norm). 

Việc tính toán độ dài (độ lớn) của vector thường được dùng như một phép chuẩn hóa trong machine learning, hoặc là một phần của các phép toán vector hoặc ma trận. Có nhiều cách khác nhau để tính độ dài (độ lớn) của vector, được gọi là vector norm.

Một số vector norm thông dụng như sau:
- L1 norm: tính tổng các giá trị tuyệt đối.
- L2 norm: Căn bậc 2 của tổng các giá trị bình phương.
- Max norm: các giá trị vector lớn nhất.

### Vector L1 norm
$$
L1(v) = ||v||_1
$$  
$$
||v||_1 = |a_1| + |a_2| + ... + |a_n|
$$

In [31]:
from numpy.linalg import norm

In [32]:
a = np.array([2, 4, 6])
l1 = norm(a, 1) # tham số thứ để cho biết hàm norm sử dụng cách tính độ lớn nào
print(l1)

12.0


### Vector L2 norm
$$
L2(v) = ||v||_2
$$
$$
||v||_2 = \sqrt{a^2_1+a^2_2+...+a^2_n}
$$

In [33]:
a = np.array([2, 4, 6])
l1 = norm(a, 2) # tham số thứ để cho biết hàm norm sử dụng cách tính độ lớn nào
print(l1)

7.483314773547883


### Vector max norm

$$
L_{inf}(v) = ||v||_{inf}
$$ 

$$
||v||_{inf} = max(a_1, a_2, ..., a_n)
$$

In [34]:
import math

a = np.array([2, 4, 6])
l1 = norm(a, math.inf) 
print(l1)

6.0


# 5. Matrix

Ma trận là một mảng hai chiều các giá trị vô hướng với một hoặc nhiều cột và dòng.

Tên của một ma trận là chữ in hoa: A

Cũng như vector ma trận được biểu diễn theo chiều nang hoặc dọc như sau:
$$
A = ((a_{1,1}, a_{1,2}, ..., a_{1, n}), (a_{2,1}, a_{2,2}, ..., a_{2, n}), ..., (a_{m,1]}, a_{m,2}, ..., a_{m, n}))
$$

$$
A = \left(
\begin{array}\
a_{1,1} & a_{1, 2} & ... & a_{1,n} \\
a_{2,1} & a_{2, 2} & ... & a_{2,n} \\
... & ... & ... & ... \\
a_{m,1} & a_{m, 2} & ... & a_{m,n} \\
\end{array}\right)
$$

## a. Tạo ma trận

In [39]:
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


## b. Các phép toán số học

### Cộng hai matrix
$$
C = A + B
$$

$$
C = 
\left(\begin{array}\
a_{1,1}+b_{1,1} & a_{1, 2}+b_{1,2} & ... & a_{1,n}+b_{1,n} \\
a_{2,1}+b_{2,1} & a_{2, 2}+b_{2,2} & ... & a_{2,n}+b_{2,n} \\
... & ... & ... & ... \\
a_{m,1}+b_{m,1} & a_{m, 2}+b_{m,2} & ... & a_{m,n}+b_{m,n} \\
\end{array}\right)
$$

In [40]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[4, 5, 6], [6, 7, 8]])
C = A + B 
print(C)

[[ 5  7  9]
 [ 9 11 13]]


### Trừ hai matrix
$$
C = A - B
$$

$$
C = 
\left(\begin{array}\
a_{1,1}-b_{1,1} & a_{1, 2}-b_{1,2} & ... & a_{1,n}-b_{1,n} \\
a_{2,1}-b_{2,1} & a_{2, 2}-b_{2,2} & ... & a_{2,n}-b_{2,n} \\
... & ... & ... & ... \\
a_{m,1}-b_{m,1} & a_{m, 2}-b_{m,2} & ... & a_{m,n}-b_{m,n} \\
\end{array}\right)
$$

In [41]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[4, 5, 6], [6, 7, 8]])
C = B - A 
print(C)

[[3 3 3]
 [3 3 3]]


### Elementwise multiplication (Hadamard product)
$$
C = A * B
$$

$$
C = 
\left(\begin{array}\
a_{1,1}*b_{1,1} & a_{1, 2}*b_{1,2} & ... & a_{1,n}*b_{1,n} \\
a_{2,1}*b_{2,1} & a_{2, 2}*b_{2,2} & ... & a_{2,n}*b_{2,n} \\
... & ... & ... & ... \\
a_{m,1}*b_{m,1} & a_{m, 2}*b_{m,2} & ... & a_{m,n}*b_{m,n} \\
\end{array}\right)
$$

In [43]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[4, 5, 6], [6, 7, 8]])
C = A * B 
print(C)

[[ 4 10 18]
 [18 28 40]]


### Elementwise divison
$$
C = A / B
$$

$$
C = 
\left(\begin{array}\
a_{1,1}/b_{1,1} & a_{1, 2}/b_{1,2} & ... & a_{1,n}/b_{1,n} \\
a_{2,1}/b_{2,1} & a_{2, 2}/b_{2,2} & ... & a_{2,n}/b_{2,n} \\
... & ... & ... & ... \\
a_{m,1}/b_{m,1} & a_{m, 2}/b_{m,2} & ... & a_{m,n}/b_{m,n} \\
\end{array}\right)
$$

In [44]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[4, 5, 6], [6, 7, 8]])
C = B / A
print(C)

[[4.   2.5  2.  ]
 [2.   1.75 1.6 ]]


### Matrix-Matrix multiplication
Nhân hai ma trận với kích thước khác nhau thỏa mãn: A(m,n) * B(b,z) = C(m,z)
$$
A = 
\left(\begin{array}\
a_{1,1} & a_{1, 2} \\
a_{2,1} & a_{2, 2} \\
a_{3, 1} & a_{3, 2}
\end{array}\right)
$$
$$
B = 
\left(\begin{array}\
b_{1,1} & b_{1, 2} \\
b_{2,1} & b_{2, 2} \\
\end{array}\right)
$$
$$
C = 
\left(\begin{array}\
a_{1,1}*b_{1,1} + a_{1, 2}*b_{2,1} &  a_{1,1}*b_{1,2} + a_{1, 2}*b_{2,2}\\
a_{2,1}*b_{1,1} + a_{2, 2}*b_{2,1} &  a_{2,1}*b_{1,2} + a_{2, 2}*b_{2,2}\\
a_{3,1}*b_{1,1} + a_{3, 2}*b_{2,1} &  a_{3,1}*b_{1,2} + a_{3, 2}*b_{2,2}\\
\end{array}\right)
$$

In [47]:
A = np.random.random((10, 12))
B = np.random.random((12, 2))

In [58]:
%%time
C = A.dot(B)

CPU times: user 44 µs, sys: 0 ns, total: 44 µs
Wall time: 48.9 µs


In [57]:
%%time
C = A @ B

CPU times: user 61 µs, sys: 7 µs, total: 68 µs
Wall time: 73.2 µs


### Matrix-Scalar Multiplication
Tương tự với vector ta có thể nhân ma trận với một giá trị vô hướng sử dụng dấu "." giữa ma trận và giá trị vô hướng
$$
C = A.b
$$

In [59]:
A = np.array([[1, 2, 3], [3, 4, 5]])
b = 5

In [66]:
%%time 
C = A.dot(b)

CPU times: user 39 µs, sys: 4 µs, total: 43 µs
Wall time: 48.9 µs


In [67]:
%%time
C = A*b

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 39.3 µs


## c. Phân loại matrix

### Ma trận vuông (Square matrix)
Là ma trận có số dòng bằng số cột: n = m 
$$
A = 
\left(\begin{array}\
1 & 2 & 3 \\
2 & 3 & 4 \\
3 & 4 & 5
\end{array}\right)
$$


### Ma trận đối xứng (Symmetric matrix)
Là ma trận có tam giác top-right gióng với tam giác bottom-left
$$
A = 
\left(\begin{array}\
2 & 4 & 6 \\
4 & 4 & 3 \\
6 & 3 & 2
\end{array}\right)
$$

### Ma trận tam giác (Triangular matrix)
Là một loại ma trận vuông mà tất cả các phần tử ở upper-right hoặc lower-left có giá trị khác 0 và phần còn lại chứa giá trị 0.

Một ma trận tam giác với các giá trị chỉ nằm trên đường chéo chính được gọi là ma trận tam giác trên (upper triangular matrix). Trong khi đó, một ma trận tam giác với các giá trị chỉ nằm dưới đường chéo chính được gọi là ma trận tam giác dưới (lower triangular matrix)

In [68]:
from numpy import tril, triu

In [69]:
A = np.array([[2, 4, 6], [4, 4, 3], [6, 3, 2]])

In [70]:
lower_tri_matrix = tril(A)
lower_tri_matrix

array([[2, 0, 0],
       [4, 4, 0],
       [6, 3, 2]])

In [71]:
upper_tri_matrix = triu(A)
upper_tri_matrix

array([[2, 4, 6],
       [0, 4, 3],
       [0, 0, 2]])

### Ma trận đường chéo (Diagonal matrix)
Là ma trận mà các giá trị ngoài đường chéo chính đều bằng 0.

Được biểu diễn bằng biến D, có thể viết đầy đủ ma trận hoặc viết gọn dưới dạng vector các giá trị. Thường sẽ sử dụng lưu trữ ma trận đường chéo dưới dạng vector để tối ưu bộ nhớ.

$$
A = 
\left(\begin{array}\
1 & 0 & 0 \\
0 & 3 & 0 \\
0 & 0 & 5
\end{array}\right)
$$

In [74]:
from numpy import diag

D = diag(A)
D

array([2, 4, 2])

### Ma trận đơn vị (Identity matrix)
Là ma trận vuông không thay đổi một vector khi nhân vector với ma trận này. Các giá trị của ma trận đơn vị được xác định là các giá trị trên đường chéo chính bằng 1 còn những giá trị còn lại bằng 0

$$
A = 
\left(\begin{array}\
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right)
$$

In [75]:
from numpy import identity 
I = identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## d. Một số thao tác trên matrix

### Chuyển vị (Transpose)
Một ma trận có thể được chuyển vị để tạo thành một ma trận mới với số dòng => số cột và ngược lại.

Ký hiệu: dùng T để cho biết việc chuyển vị
$$
C = A^T
$$

In [76]:
A = np.array([[1, 2, 3], [4, 5, 6]])
C = A.T
print(C)

[[1 4]
 [2 5]
 [3 6]]


### Nghịch đảo (Inverse)
Nghịch đảo ma trận là một quá trình tìm một ma trận mà khi nhân ma trận này với một ma trận khác sẽ có kết quả là identity matrix. Cho matrix A (vuông), tìm matrix B sao cho $AB=I^n$ hoặc $BA=I^n$

Ma trận nghịch đảo B từ A: $B=A^{-1}$

In [77]:
from numpy.linalg import inv 

In [80]:
A = np.array([[1, 2], [4, 5]])
B = inv(A)
B

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [81]:
I = A.dot(B)
I

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

### Trace
Trace của ma trận là tổng các phần tử trên đường chéo chính của ma trận vuông.
$$
tr(A) = a_{1,1} + a_{2,2}+ ... + a_{n,n}
$$

In [82]:
A = np.array([[1, 2], [4, 5]])
trace_A = np.trace(A)
trace_A

6

### Định thức (Determinant)

Định thức của ma trận vuông A là một giá trị vô hướng được tính như hình sau:
$$
A = 
\left(\begin{array}\
a_{1,1} & a_{1, 2} & a_{1, 3} \\
a_{2,1} & a_{2, 2} & a_{2, 3}\\
a_{3, 1} & a_{3, 2} & a_{3, 3}
\end{array}\right)
= a_{1,1}a_{2,2}a_{3,3}+a_{1,2}a_{2,3}a_{3,1}+a_{1,3}a_{2,1}a_{3,2}-a_{1,3}a_{2,2}a_{3,1}-a_{1,2}a_{2,1}a{3_3}-a_{1,1}a_{2,3}a_{3,2}
$$

Ký hiệu: del(A) hoặc |A|






In [84]:
from numpy.linalg import det
A = np.array([[1, 2, 3], [3, 4, 5], [5, 8, 9]])
det_A = det(A)
det_A

4.0000000000000036

### Hạng của ma trận
- Hạng của ma trận là ước tính số lượng hàng hoặc cột độc lập tuyến tính trong ma trận.
- Cú pháp: rank(A)

In [85]:
from numpy.linalg import matrix_rank 
A = np.array([[1, 2, 3], [3, 4, 5], [5, 8, 9]])
matrix_rank_A = matrix_rank(A)
matrix_rank_A

3